package com.vod.event.listner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.hazelcast.logging.LogEvent;
import com.vod.event.model.Event;
import com.vod.event.model.EventLog;
import com.vod.event.model.EventLogReq;
import com.vod.event.service.EventLogService;

@Service
public class EventLogListener {

	private final Logger logger = LoggerFactory.getLogger(this.getClass());

	@Autowired
	private EventLogService eventLogService;
	
	@RabbitListener(queues = "appevent_queue")
	public void listen(EventLogReq  req) {
	   
		logger.info("Event Log Received generated by User:"+req.getReqUserID());
		try {
			
			eventLogService.processEventLog(req);
		}
		catch(Exception e)
		{
			logger.info(e.getMessage(), e);
			
		}
		
	}
}
